from __future__ import annotations

import shutil
import sqlite3
from pathlib import Path

import pytest

from waloader.config import WALoaderConfig
from waloader.models import User
from waloader.repositories import apps as apps_repo
from waloader.services import caddy


def _config(tmp_path: Path) -> WALoaderConfig:
    return WALoaderConfig.model_validate(
        {"paths": {"data_dir": str(tmp_path / "data")}, "caddy": {"enabled": True}}
    )


@pytest.fixture
def populated(conn: sqlite3.Connection, user: User) -> sqlite3.Connection:
    a = apps_repo.create(conn, owner_id=user.id, name="Alpha", slug="alpha")
    apps_repo.set_port(conn, a.id, 8601)
    b = apps_repo.create(conn, owner_id=user.id, name="Beta", slug="beta")
    apps_repo.set_port(conn, b.id, 8602)
    apps_repo.create(conn, owner_id=user.id, name="NoPort", slug="no-port")
    d = apps_repo.create(conn, owner_id=user.id, name="Gone", slug="gone")
    apps_repo.set_port(conn, d.id, 8603)
    apps_repo.mark_deleted(conn, d.id, archive_path="x", purge_after="2099-01-01")
    conn.commit()
    return conn


class TestGeneration:
    def test_routes_and_structure(self, populated: sqlite3.Connection,
                                  tmp_path: Path) -> None:
        config = _config(tmp_path)
        text = caddy.generate_caddyfile(populated, config)
        assert "admin localhost:2019" in text
        assert ":8080 {" in text
        assert "redir / /waloader/ 302" in text
        assert "handle /waloader*" in text
        assert "reverse_proxy 127.0.0.1:8501" in text
        assert "handle /apps/alpha*" in text and "reverse_proxy 127.0.0.1:8601" in text
        assert "handle /apps/beta*" in text and "reverse_proxy 127.0.0.1:8602" in text
        assert "no-port" not in text  # apps without ports get no route
        assert "gone" not in text  # deleted apps get no route
        assert 'respond "WALoader: unknown route" 404' in text
        assert "access.log" in text

    def test_write(self, populated: sqlite3.Connection, tmp_path: Path) -> None:
        config = _config(tmp_path)
        path = caddy.write_caddyfile(populated, config)
        assert path == config.caddy_config_path
        assert "Generated by WALoader" in path.read_text()

    def test_validate_missing_file(self, tmp_path: Path) -> None:
        result = caddy.validate(_config(tmp_path))
        assert not result.ok and "No generated Caddyfile" in result.output


class TestStatus:
    def test_status_shape(self, populated: sqlite3.Connection, tmp_path: Path) -> None:
        config = _config(tmp_path)
        info = caddy.status(populated, config)
        assert info["enabled"] is True
        assert info["running"] is False
        assert info["routes"] == 2
        assert info["config_exists"] is False

    def test_stop_when_not_running_is_ok(self, tmp_path: Path) -> None:
        result = caddy.stop(_config(tmp_path))
        assert result.ok and "was not running" in result.output

    def test_reload_when_not_running_fails_clearly(
        self, populated: sqlite3.Connection, tmp_path: Path
    ) -> None:
        result = caddy.reload(populated, _config(tmp_path))
        assert not result.ok and "not running" in result.output

    def test_refresh_routes_without_caddy_regenerates(
        self, populated: sqlite3.Connection, tmp_path: Path
    ) -> None:
        config = _config(tmp_path)
        result = caddy.refresh_routes(populated, config)
        assert result.ok and config.caddy_config_path.exists()


@pytest.mark.caddy
class TestWithRealBinary:
    def test_generated_config_passes_caddy_validate(
        self, populated: sqlite3.Connection, tmp_path: Path
    ) -> None:
        if shutil.which("caddy") is None:
            pytest.skip("caddy binary not on PATH")
        config = _config(tmp_path)
        caddy.write_caddyfile(populated, config)
        result = caddy.validate(config)
        assert result.ok, f"caddy validate rejected our config:\n{result.output}"
