"""Caddy reverse proxy: Caddyfile generation from the DB + process wrapper.

The Caddyfile is fully generated — operators never hand-edit it. Caddy itself
runs as a managed detached child (no root, no systemd), tracked by a pidfile
(pid + create_time) beside the generated config.
"""

from __future__ import annotations

import json
import logging
import sqlite3
import subprocess
from dataclasses import dataclass
from pathlib import Path

from waloader.config import WALoaderConfig
from waloader.paths import ensure_dir
from waloader.repositories import apps as apps_repo
from waloader.services import processes
from waloader.services.uv_env import redact

log = logging.getLogger(__name__)

CADDY_TIMEOUT = 30


class CaddyNotConfiguredError(Exception):
    pass


@dataclass
class CaddyResult:
    ok: bool
    output: str = ""


def caddy_binary(config: WALoaderConfig) -> str:
    binary = config.resolved_caddy()
    if binary is None:
        raise CaddyNotConfiguredError(
            "No Caddy binary found. Set executables.caddy_binary or put 'caddy' on PATH."
        )
    return binary


def generate_caddyfile(conn: sqlite3.Connection, config: WALoaderConfig) -> str:
    """Routes: /waloader -> WALoader UI; /apps/<slug> -> each child app port."""
    logs_dir = config.caddy_logs_dir
    lines = [
        "# Generated by WALoader — do not edit by hand; regenerate via caddyctl/admin panel.",
        "{",
        f"    admin localhost:{config.caddy.admin_port}",
        "}",
        "",
        f":{config.ports.caddy_public_port} {{",
        "    log {",
        f"        output file {(logs_dir / 'access.log').as_posix()}",
        "    }",
        "",
        "    redir / /waloader/ 302",
        "    handle /waloader* {",
        f"        reverse_proxy 127.0.0.1:{config.ports.waloader_port}",
        "    }",
    ]
    for app in apps_repo.list_all(conn):
        if app.port is None:
            continue
        lines += [
            f"    handle /apps/{app.slug}* {{",
            f"        reverse_proxy 127.0.0.1:{app.port}",
            "    }",
        ]
    lines += [
        "    handle {",
        '        respond "WALoader: unknown route" 404',
        "    }",
        "}",
        "",
    ]
    return "\n".join(lines)


def write_caddyfile(conn: sqlite3.Connection, config: WALoaderConfig) -> Path:
    path = config.caddy_config_path
    ensure_dir(path.parent)
    ensure_dir(config.caddy_logs_dir)
    path.write_text(generate_caddyfile(conn, config), encoding="utf-8")
    log.info("caddyfile written: %s", path)
    return path


def _run_caddy(config: WALoaderConfig, *args: str) -> CaddyResult:
    try:
        command = [caddy_binary(config), *args]
    except CaddyNotConfiguredError as exc:
        return CaddyResult(False, str(exc))
    try:
        completed = subprocess.run(  # noqa: S603 - argv list, no shell
            command, capture_output=True, text=True, timeout=CADDY_TIMEOUT
        )
    except subprocess.TimeoutExpired:
        return CaddyResult(False, f"caddy {' '.join(args)} timed out after {CADDY_TIMEOUT}s")
    output = redact((completed.stdout + "\n" + completed.stderr).strip())
    return CaddyResult(completed.returncode == 0, output)


def validate(config: WALoaderConfig) -> CaddyResult:
    path = config.caddy_config_path
    if not path.exists():
        return CaddyResult(False, f"No generated Caddyfile at {path}; run generate first.")
    return _run_caddy(config, "validate", "--config", str(path))


def _pidfile(config: WALoaderConfig) -> Path:
    return config.caddy_config_path.parent / "caddy.pid.json"


def _read_pidfile(config: WALoaderConfig) -> tuple[int, float] | None:
    path = _pidfile(config)
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return int(data["pid"]), float(data["create_time"])
    except (ValueError, KeyError, json.JSONDecodeError):
        return None


def is_running(config: WALoaderConfig) -> bool:
    record = _read_pidfile(config)
    return record is not None and processes.pid_matches(*record)


def start(conn: sqlite3.Connection, config: WALoaderConfig) -> CaddyResult:
    if is_running(config):
        return CaddyResult(True, "caddy already running")
    try:
        binary = caddy_binary(config)
    except CaddyNotConfiguredError as exc:
        return CaddyResult(False, str(exc))
    path = write_caddyfile(conn, config)
    check = validate(config)
    if not check.ok:
        return CaddyResult(False, f"Generated Caddyfile failed validation:\n{check.output}")
    import os

    pid, create_time = processes.spawn_detached(
        [binary, "run", "--config", str(path)],
        cwd=path.parent,
        env=dict(os.environ),
        log_file=config.caddy_logs_dir / "caddy.log",
    )
    _pidfile(config).write_text(
        json.dumps({"pid": pid, "create_time": create_time}), encoding="utf-8"
    )
    return CaddyResult(True, f"caddy started (pid {pid}) on :{config.ports.caddy_public_port}")


def stop(config: WALoaderConfig) -> CaddyResult:
    record = _read_pidfile(config)
    if record is None or not processes.pid_matches(*record):
        _pidfile(config).unlink(missing_ok=True)
        return CaddyResult(True, "caddy was not running")
    processes.terminate_tree(record[0], record[1], timeout=10)
    _pidfile(config).unlink(missing_ok=True)
    return CaddyResult(True, "caddy stopped")


def reload(conn: sqlite3.Connection, config: WALoaderConfig) -> CaddyResult:
    """Regenerate the Caddyfile and hot-reload via Caddy's admin API."""
    path = write_caddyfile(conn, config)
    if not is_running(config):
        return CaddyResult(False, "caddy is not running; use start instead")
    return _run_caddy(config, "reload", "--config", str(path))


def refresh_routes(conn: sqlite3.Connection, config: WALoaderConfig) -> CaddyResult:
    """Deployment hook: regenerate and reload if running, else just regenerate."""
    if is_running(config):
        return reload(conn, config)
    write_caddyfile(conn, config)
    return CaddyResult(True, "caddyfile regenerated (caddy not running)")


def status(conn: sqlite3.Connection, config: WALoaderConfig) -> dict:
    record = _read_pidfile(config)
    running = record is not None and processes.pid_matches(*record)
    return {
        "enabled": config.caddy.enabled,
        "running": running,
        "pid": record[0] if record and running else None,
        "binary": config.resolved_caddy(),
        "config_path": str(config.caddy_config_path),
        "config_exists": config.caddy_config_path.exists(),
        "public_port": config.ports.caddy_public_port,
        "routes": len(
            [a for a in apps_repo.list_all(conn) if a.port is not None]
        ),
    }
